# Generated by Django 4.2.30 on 2026-05-28 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Procurement'), ('UTILITY', 'Utility Meters'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('ingested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(help_text='e.g., company.com', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_reference_id', models.CharField(help_text='Original row ID from source data', max_length=255)),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(help_text='FUEL, kWh, FLIGHT_KM, etc.', max_length=50)),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('activity_unit', models.CharField(help_text='L, kg, kWh, km, nights, etc.', max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect Energy'), ('SCOPE_3', 'Scope 3 - Other Indirect')], max_length=20)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('ELECTRICITY', 'Electricity'), ('FLIGHTS', 'Flight Travel'), ('HOTELS', 'Hotel Stays'), ('GROUND_TRANSPORT', 'Ground Transport'), ('OTHER', 'Other')], max_length=30)),
                ('emission_factor', models.DecimalField(decimal_places=6, help_text='CO2e factor used (kg CO2e per unit)', max_digits=15)),
                ('calculated_emissions_kg_co2e', models.DecimalField(decimal_places=4, max_digits=15)),
                ('status', models.CharField(choices=[('NEW', 'New - Awaiting Review'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('validation_issues', models.JSONField(blank=True, default=list, help_text='Array of validation issue strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOTES_ADDED', 'Notes Added')], max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of field changes: {field: {old_value, new_value}}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.rawemission')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('ANALYST', 'Analyst'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddIndex(
            model_name='rawemission',
            index=models.Index(fields=['organization', '-activity_date'], name='emissions_r_organiz_5d80b7_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemission',
            index=models.Index(fields=['organization', 'status'], name='emissions_r_organiz_3ed481_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemission',
            index=models.Index(fields=['data_source'], name='emissions_r_data_so_7645f4_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', '-ingested_at'], name='emissions_d_organiz_732846_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['emission', 'timestamp'], name='emissions_a_emissio_8e3f23_idx'),
        ),
    ]
